### ISSUE TITLE
things to check before prod

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/minecraft-data-generator-server#1]
- [x] air is not diggable
- [x] grass_block and dirt have effective tools
- [x] dont add repairWith if it's empty

**Comment by u9g** [comment]
eventually would be nice to add cake food/sat to foods.json

**Comment by u9g** [comment]
- [ ] 1.15's lootContextBuilder should add `.put(LootContextParameters.BLOCK_STATE, blockState)` ...etc

**Comment by u9g** [comment]
it's `filterLight` NOT `filtersLight`

**Comment by u9g** [comment]
- [ ] so many versions have `maxDurability` wrong, it should be item#getMaxDamage

**Comment by u9g** [comment]
- [ ] round depth to 2 decimals

**Comment by u9g** [comment]
- [ ] rename ClientSideAnnoyances to be lowercase

**Comment by u9g** [comment]
- [ ] most versions dont need MiningToolAccessor, there is a item.getEffectiveBlocks()...

**Comment by u9g** [comment]
- [ ] add attributes.json to all versions

**Comment by u9g** [comment]
- [ ] enchantment.isDifferent in EnchantmentsDataGenerator should have a not before it, ie:
```java
            if (!enchantment.isDifferent(other) && other != enchantment) {
```

**Comment by u9g** [comment]
- [ ] make sure getMaximumPower is properly used on all enchants, since it is overridden
```java
-        int b = getMaximumPower(enchantment,0);
-        int a = getMaximumPower(enchantment,1) - b;
+        int b = enchantment.getMaximumPower(0);
+        int a = enchantment.getMaximumPower(1) - b;
```

**Comment by u9g** [comment]
- [ ] remove SkyColors from 1.11.2

**Comment by u9g** [comment]
- [ ] remove stackSize from blocks.json in all versions

**Comment by u9g** [comment]
- [ ] remove this comment
```
        // FIXME: ENTITY ID IS WRONG
```

**Comment by u9g** [comment]
- [ ] `vanishable` should not be in the `enchantCategories` for all items in `items.json`...

**Comment by u9g** [comment]
- [ ] make sure BlockDataDumper's emitLight is correct for all versions

**Comment by u9g** [comment]
- [ ] replace `DGU.getCurrentlyRunningServer().stopServer();` with `System.exit(0)` everywhere

**Comment by rom1504** [comment]
@AlexProgrammerDE any thoughts on those ?

**Comment by rom1504** [comment]
I think this is basically done
